### ISSUE TITLE
人物称呼

### ISSUE THREAD

**Issue by cszhxn** [biemote/Asura-s-Wrath_Chinese-Localization-Text#22]
有几个称呼感觉在中文里不合适，
伯父大人（其实是舅舅，不需要按原文翻译，直接改舅舅即可）
笔头（又不是战国游戏，没必要按原文）
喷帝（中文太难听，建议改成弗栗多核心）
转轮王 阿 修罗（容易让人产生联想误解，b站很多人就说是主角前世，直接改成造物主 转轮王，比较合适）
个人意见，仅供参考。

**Comment by Biemote** [comment]
你好哦~

1、`伯父大人`已全部修正为`舅父大人`，`伯父大人`为翻译错误。
2、德乌斯的`七星天筆頭`已全部翻译作`七星天首领`，但神国士兵的称呼为游戏设定上的专有名词（详情请参考游戏的额外内容内文本），因此不作修改。
3、`噴帝 ヴリトラ`为游戏设定上的专有名词，不作修改。
4、`転輪王 ア・スラ`译作`轮转王 阿·修罗`是有实际考据的翻译文本，不作修改。
